volumes:
  core_local_static: {}
  core_local_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: core_local_django
    container_name: core_local_django
    volumes:
      - .:/app:z
      - core_local_static:/app/staticfiles
      - core_local_media:/app/core/media
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start
