volumes:
  core_local_postgres_data: {}
  core_local_postgres_data_backups: {}
  core_local_static: {}
  core_local_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: core_local_django
    container_name: core_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
      - core_local_static:/app/staticfiles
      - core_local_media:/app/core/media
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: core_production_postgres
    container_name: core_local_postgres
    volumes:
      - core_local_postgres_data:/var/lib/postgresql/data
      - core_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
